### ISSUE TITLE
Glee V1.0.0 planning

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/glee#477]
> I am opening this issue to basically start the conversation and ultimately define what glee `V1.0.0` would look like. Version one's goal is to get Glee production ready which will help us gain new users. 

### Features
- [ ] Updating Documentation - https://github.com/asyncapi/glee/issues/431 selected for the mentorship program. 
- [ ] Add required support for existing adapters
  - [ ] Authentication support for server and client - https://github.com/asyncapi/glee/issues/377 selected for GSoC 2023
  - [ ] https://github.com/asyncapi/glee/issues/411
 - [x] https://github.com/asyncapi/glee/issues/409
 - [ ] https://github.com/asyncapi/glee/issues/391
 - [x] https://github.com/asyncapi/cli/issues/683
 - [ ]  https://github.com/asyncapi/glee/issues/457 (Not confirmed up for debate)
### Bug Fixes 
  - [x] https://github.com/asyncapi/glee/issues/461
  - [x] https://github.com/asyncapi/glee/issues/475
    - we might have more bugs, we are testing and finding these out. 

> These are some of the work that we can add, @KhudaDad414 you can add anything else you like.

**Comment by KhudaDad414** [comment]
should we consider this as well https://github.com/asyncapi/cli/issues/683? 🤔
